language: java

jdk:
  - openjdk11

addons:
  sonarcloud:
    organization: exasol

install:
  - travis_retry mvn dependency:resolve

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml,target/site/jacoco-it/jacoco.xml

cache:
  directories:
    - "$HOME/.m2"